apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-system-deployment
  labels:
    app: ticketing-system
spec:
  replicas: 5
  selector:
    matchLabels:
      app: ticketing-system
  template:
    metadata:
      labels:
        app: ticketing-system
    spec:
      containers:
      - name: ticketing-system
        image: rvp0110/ticketing-system:v5
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---



            