apiVersion: v1
kind: Service
metadata:
  name: ticketing-system-service
spec:
  type: NodePort
  selector:
    app: ticketing-system
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007